/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-food': '&#x1f558;',
		'icon-lunch': '&#x1f558;',
		'icon-soup': '&#x1f558;',
		'icon-book2': '&#xe905;',
		'icon-stopwatch': '&#xe904;',
		'icon-bolt': '&#xe91d;',
		'icon-graph': '&#xe91f;',
		'icon-book': '&#xf02d;',
		'icon-calendar': '&#xf073;',
		'icon-trophy': '&#xf091;',
		'icon-chain': '&#xf0c1;',
		'icon-link2': '&#xf0c1;',
		'icon-comment-o': '&#xf0e5;',
		'icon-comments-o': '&#xf0e6;',
		'icon-sitemap': '&#xf0e8;',
		'icon-lightbulb-o': '&#xf0eb;',
		'icon-coffee': '&#xf0f4;',
		'icon-pencil-square': '&#xf14b;',
		'icon-cc-visa': '&#xf1f0;',
		'icon-cc-mastercard': '&#xf1f1;',
		'icon-cc-paypal': '&#xf1f4;',
		'icon-user-plus2': '&#xf234;',
		'icon-user-times': '&#xf235;',
		'icon-map-o': '&#xf278;',
		'icon-map': '&#xf279;',
		'icon-shopping-basket': '&#xf291;',
		'icon-id-badge': '&#xf2c1;',
		'icon-drivers-license-o': '&#xf2c3;',
		'icon-id-card-o': '&#xf2c3;',
		'icon-chevron-small-down': '&#xe900;',
		'icon-chevron-small-left': '&#xe901;',
		'icon-chevron-small-right': '&#xe902;',
		'icon-chevron-small-up': '&#xe903;',
		'icon-upload-to-cloud': '&#xe920;',
		'icon-add-user': '&#xe906;',
		'icon-blackboard': '&#xe907;',
		'icon-bowl': '&#xe908;',
		'icon-cake': '&#xe909;',
		'icon-chat': '&#xe90a;',
		'icon-check': '&#xe90b;',
		'icon-circle-with-cross': '&#xe90c;',
		'icon-circle-with-minus': '&#xe90d;',
		'icon-circle-with-plus': '&#xe90e;',
		'icon-clock': '&#xe911;',
		'icon-cog2': '&#xe912;',
		'icon-credit-card': '&#xe913;',
		'icon-credit': '&#xe914;',
		'icon-cycle': '&#xe915;',
		'icon-drink': '&#xe916;',
		'icon-home': '&#xe917;',
		'icon-key': '&#xe918;',
		'icon-line-graph': '&#xe919;',
		'icon-location-pin': '&#xe91a;',
		'icon-location': '&#xe91c;',
		'icon-camera': '&#xe90f;',
		'icon-headphones': '&#xe910;',
		'icon-connection': '&#xe91b;',
		'icon-mic': '&#xe91e;',
		'icon-library': '&#xe921;',
		'icon-file-text2': '&#xe926;',
		'icon-folder': '&#xe92f;',
		'icon-folder-open': '&#xe930;',
		'icon-cart': '&#xe93a;',
		'icon-coin-dollar': '&#xe93b;',
		'icon-address-book': '&#xe944;',
		'icon-location2': '&#xe948;',
		'icon-clock2': '&#xe94f;',
		'icon-alarm': '&#xe950;',
		'icon-bell': '&#xe951;',
		'icon-bubbles': '&#xe96c;',
		'icon-user': '&#xe971;',
		'icon-user-plus': '&#xe973;',
		'icon-user-minus': '&#xe974;',
		'icon-user-check': '&#xe975;',
		'icon-search': '&#xe986;',
		'icon-key2': '&#xe98e;',
		'icon-cog': '&#xe994;',
		'icon-stats-dots': '&#xe99b;',
		'icon-glass': '&#xe9a0;',
		'icon-glass2': '&#xe9a1;',
		'icon-mug': '&#xe9a2;',
		'icon-spoon-knife': '&#xe9a3;',
		'icon-fire': '&#xe9a9;',
		'icon-truck': '&#xe9b0;',
		'icon-target': '&#xe9b3;',
		'icon-menu': '&#xe9bd;',
		'icon-cloud-download': '&#xe9c2;',
		'icon-cloud-upload': '&#xe9c3;',
		'icon-cloud-check': '&#xe9c4;',
		'icon-earth': '&#xe9ca;',
		'icon-link': '&#xe9cb;',
		'icon-star-empty': '&#xe9d7;',
		'icon-star-half': '&#xe9d8;',
		'icon-star-full': '&#xe9d9;',
		'icon-heart': '&#xe9da;',
		'icon-happy': '&#xe9df;',
		'icon-smile': '&#xe9e1;',
		'icon-tongue': '&#xe9e3;',
		'icon-sad': '&#xe9e5;',
		'icon-wink': '&#xe9e7;',
		'icon-angry': '&#xe9ed;',
		'icon-shocked': '&#xe9f1;',
		'icon-baffled': '&#xe9f3;',
		'icon-confused': '&#xe9f5;',
		'icon-neutral': '&#xe9f7;',
		'icon-frustrated': '&#xe9ff;',
		'icon-crying': '&#xea01;',
		'icon-plus': '&#xea0a;',
		'icon-minus': '&#xea0b;',
		'icon-cross': '&#xea0f;',
		'icon-checkmark': '&#xea10;',
		'icon-pause2': '&#xea1d;',
		'icon-stop2': '&#xea1e;',
		'icon-backward2': '&#xea1f;',
		'icon-forward3': '&#xea20;',
		'icon-first': '&#xea21;',
		'icon-last': '&#xea22;',
		'icon-eject': '&#xea25;',
		'icon-volume-high': '&#xea26;',
		'icon-volume-low': '&#xea28;',
		'icon-volume-mute2': '&#xea2a;',
		'icon-move-up': '&#xea46;',
		'icon-move-down': '&#xea47;',
		'icon-sort-alpha-asc': '&#xea48;',
		'icon-sort-alpha-desc': '&#xea49;',
		'icon-sort-numeric-asc': '&#xea4a;',
		'icon-sort-numberic-desc': '&#xea4b;',
		'icon-sort-amount-asc': '&#xea4c;',
		'icon-sort-amount-desc': '&#xea4d;',
		'icon-table2': '&#xea71;',
		'icon-facebook2': '&#xea91;',
		'icon-whatsapp': '&#xea93;',
		'icon-twitter': '&#xea96;',
		'icon-file-pdf': '&#xeadf;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
